blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PublicationCreateView, PublicationListView, PublicationDetailView, PublicationUpdateView, \
    PublicationDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PublicationCreateView.as_view(), name='create'),
    path('', PublicationListView.as_view(), name='list'),
    path('view/<int:pk>', PublicationDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PublicationUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PublicationDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from mailings.services import start_apscheduler
from mailings.apps import MailingsConfig
from config.settings import AUTO_MAILING

from mailings.views import (MailingListView, MailingUpdateView, MailingDetailView, MailingDeleteView, MailingCreateView,
                            MailingMessageListView, MailingMessageUpdateView, MailingMessageDetailView,
                            MailingMessageDeleteView, MailingMessageCreateView, RecipientClientListView,
                            RecipientClientUpdateView, RecipientClientDetailView, RecipientClientDeleteView,
                            RecipientClientCreateView, MailingHistoryListView, MailingHistoryDetailView,
                            MailingHistoryDeleteView)

app_name = MailingsConfig.name

if AUTO_MAILING:
    start_apscheduler()

urlpatterns = [
    path('', MailingListView.as_view(), name='mailings_list'),
    path('message_list/', MailingMessageListView.as_view(), name='message_list'),
    path('clients_list/', RecipientClientListView.as_view(), name='clients_list'),
    path('history_list/', MailingHistoryListView.as_view(), name='history_list'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('message_update/<int:pk>', MailingMessageUpdateView.as_view(), name='message_update'),
    path('clients_update/<int:pk>', RecipientClientUpdateView.as_view(), name='clients_update'),
    path('mailing_detail/<int:pk>', MailingDetailView.as_view(), name='mailing_detail'),
    path('message_detail/<int:pk>', MailingMessageDetailView.as_view(), name='message_detail'),
    path('clients_detail/<int:pk>', RecipientClientDetailView.as_view(), name='clients_detail'),
    path('history_detail/<int:pk>', MailingHistoryDetailView.as_view(), name='history_detail'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message_delete/<int:pk>', MailingMessageDeleteView.as_view(), name='message_delete'),
    path('clients_delete/<int:pk>', RecipientClientDeleteView.as_view(), name='clients_delete'),
    path('history_delete/<int:pk>', MailingHistoryDeleteView.as_view(), name='history_delete'),
    path('create/', MailingCreateView.as_view(), name='create_mailing'),
    path('create_message/', MailingMessageCreateView.as_view(), name='create_message'),
    path('create_client/', RecipientClientCreateView.as_view(), name='create_client')
]

mailings/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}
PERIODICITY_DATA = {
    'раз в день': 'день',
    'раз в неделю': 'неделя',
    'раз в месяц': 'месяц'
}
STATUS_DATA = {
    'завершена': 'завершена',
    'создана': 'создана',
    'запущена': 'запущена',
}

class MailingMessage(models.Model):
    theme = models.CharField(max_length=100, verbose_name='тема письма')
    body = models.CharField(max_length=150, verbose_name='тело письма')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.theme}'

    owner = models.ForeignKey(User, on_delete=models.CASCADE, help_text='укажите владельца', verbose_name='владелец',
                              **NULLABLE)

    class Meta:
        verbose_name = 'Сообщение рассылки'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Сообщения рассылки'  # Настройка для наименования набора объектов

class RecipientClient(models.Model):
    email = models.EmailField(unique=True, verbose_name='email')
    full_name = models.CharField(max_length=150, verbose_name='ф.и.о')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, help_text='укажите владельца', verbose_name='владелец',
                              **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.full_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент получатель'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Клиенты получатели'  # Настройка для наименования набора объектов
        permissions = [
            ('can_edit_email', 'Can edit email'),
            ('can_edit_full_name', 'Can edit full_name'),
            ('can_edit_comment', 'Can edit comment')
        ]

class Mailing(models.Model):
    first_date = models.DateField(verbose_name='дата первой отправки. Формат: 2024-06-13')
    periodicity = models.CharField(choices=PERIODICITY_DATA, verbose_name='периодичность')
    check_periodicity = models.IntegerField(default='0', verbose_name='дней до следующей отправки')
    status = models.CharField(choices=STATUS_DATA, default='создана', verbose_name='статус', **NULLABLE)
    message = models.ForeignKey(MailingMessage, on_delete=models.SET_NULL, verbose_name='сообщение', **NULLABLE)
    clients = models.ManyToManyField(RecipientClient, verbose_name='клиенты')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, help_text='укажите владельца', verbose_name='владелец',
                              **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'рассылка стартовала {self.first_date}'

    class Meta:
        verbose_name = 'Рассылка'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Рассылки'  # Настройка для наименования набора объектов
        permissions = [
            ('can_edit_status', 'Can edit status'),
            ('can_edit_periodicity', 'Can edit periodicity'),
            ('can_edit_clients', 'Can edit clients')
        ]

class HistoryMailing(models.Model):
    last_date = models.DateField(verbose_name='дата последней попытки')
    status = models.BooleanField(verbose_name='статус успешно/нет')
    response = models.CharField(verbose_name='ответ почтового сервера')

mailings/forms.py
from django import forms
from django.forms import BooleanField
from mailings.models import Mailing, MailingMessage, RecipientClient



class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'
        fields = ('first_date', 'periodicity', 'message', 'clients')
        # exclude = ('name')

class MailingMessageUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = ('theme', 'body')

class RecipientClientUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = RecipientClient
        fields = ('email', 'full_name', 'comment')

mailings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView, DetailView, DeleteView, CreateView
from mailings.models import Mailing, MailingMessage, RecipientClient, HistoryMailing
from mailings.forms import MailingUpdateForm, MailingMessageUpdateForm, RecipientClientUpdateForm

# Create your views here.
class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        mailings = Mailing.objects.filter(owner=user)
        context['mailings_list'] = mailings
        return context

class MailingMessageListView(LoginRequiredMixin, ListView):
    model = MailingMessage

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        messages = MailingMessage.objects.filter(owner=user)
        context['messages'] = messages
        return context

class RecipientClientListView(LoginRequiredMixin, ListView):
    model = RecipientClient

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        clients = RecipientClient.objects.filter(owner=user)
        context['clients'] = clients
        return context

class MailingHistoryListView(LoginRequiredMixin, ListView):
    model = HistoryMailing

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        history = HistoryMailing.objects.all()
        context['history'] = history
        return context

class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingUpdateForm
    success_url = reverse_lazy('mailings:mailings_list')

    def get_success_url(self):
        return reverse('mailings:mailing_detail', args=[self.kwargs.get('pk')])

class MailingMessageUpdateView(UpdateView):
    model = MailingMessage
    form_class = MailingMessageUpdateForm
    success_url = reverse_lazy('mailings:message_list')

    def get_success_url(self):
        return reverse('mailings:message_detail', args=[self.kwargs.get('pk')])

class RecipientClientUpdateView(UpdateView):
    model = RecipientClient
    form_class = RecipientClientUpdateForm
    success_url = reverse_lazy('mailings:clients_list')

    def get_success_url(self):
        return reverse('mailings:clients_detail', args=[self.kwargs.get('pk')])

class MailingDetailView(DetailView):
    model = Mailing

class MailingMessageDetailView(DetailView):
    model = MailingMessage

class RecipientClientDetailView(DetailView):
    model = RecipientClient

class MailingHistoryDetailView(DetailView):
    model = HistoryMailing

class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailings:mailings_list')

class MailingMessageDeleteView(DeleteView):
    model = MailingMessage
    success_url = reverse_lazy('mailings:message_list')

class RecipientClientDeleteView(DeleteView):
    model = RecipientClient
    success_url = reverse_lazy('mailings:clients_list')

class MailingHistoryDeleteView(DeleteView):
    model = HistoryMailing
    success_url = reverse_lazy('mailings:history_list')

class MailingCreateView(LoginRequiredMixin,CreateView):
    model = Mailing
    form_class = MailingUpdateForm
    success_url = reverse_lazy('mailings:mailings_list')

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)

class MailingMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    form_class = MailingMessageUpdateForm
    success_url = reverse_lazy('mailings:message_list')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)

class RecipientClientCreateView(LoginRequiredMixin, CreateView):
    model = RecipientClient
    form_class = RecipientClientUpdateForm
    success_url = reverse_lazy('mailings:clients_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

mailings/templates/mailings/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <title>{{ title_name|title }}</title>
</head>
<body>
<header>
    {% include 'mailings/includes/menu.html' %}
    {% block content %}
    {% endblock %}
</header>
<footer class="text-body-secondary py-5 col-10 mx-auto">
    {% include 'mailings/includes/footer.html' %}
</footer>
<script src="{% static 'js/bootstrap.js' %}">
</script>
</body>
</html>

mailings/templates/mailings/historymailing_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h3>Хотите удалить запись из истории? от - {{ object.last_date }}</h3>
                    <button type="submit" class="btn btn-secondary">
                        Подтвердить
                    </button>
                    <a class="btn btn-success" href="{% url 'mailings:message_list' %}">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/historymailing_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h2 class="display-4 fw-normal">Статус - {{ object.status }}</h2>
</div>
<ul class="col-10 mx-auto">
    <li><b>Ответ почтового сервера</b> - {{ object.response }}</li>
    <li><b>Дата последней попытки</b> - {{ object.last_date }}</li>
</ul>
<div class="col-10 mx-auto">
    <a type="button" title="Вернуться на главную" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:history_list' %}">Назад</a>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:history_delete' object.pk %}">Удалить</a>
</div>
{% endblock %}

mailings/templates/mailings/historymailing_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h1 class="display-4 fw-normal">{{ title_name|title }} Hello</h1>
    <p class="fs-5 text-muted">История рассылок</p>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3  col-10 mx-auto">
    {% for item in history %}
    <div class="col">
        <div class="card shadow-sm" style="min-width: 304px;">
            <div class="card-body">
                <p class="card-text">Статус - {{ item.status|title }}</p>
                <p class="card-text">Дата последней попытки - {{ item.last_date }}</p>
                <div class="">
                    <div class="">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:history_detail' item.pk %}">Подробнее</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:history_delete' item.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">

        <form method="post" enctype="multipart/form-data">
            <div class="text-center">
                <p class="mt-4">Изменить данные рассылки:</p>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a type="button" title="Вернуться на главную" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'mailings:mailings_list' %}">Назад</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h1 class="display-4 fw-normal">{{ title_name|title }} Hello</h1>
    <p class="fs-5 text-muted">Список рассылок</p>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:create_mailing' %}">Добавить рассылку</a>
</div>
{% include 'mailings/includes/card.html' %}
{% endblock %}

mailings/templates/mailings/mailingmessage_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h3>Хотите удалить сообщение? {{ object.theme }}</h3>
                    <button type="submit" class="btn btn-secondary">
                        Подтвердить
                    </button>
                    <a class="btn btn-success" href="{% url 'mailings:message_list' %}">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingmessage_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h2 class="display-4 fw-normal">Тема - {{ object.theme|title }}</h2>
</div>
<ul class="col-10 mx-auto">
    <li><b>Содержание</b> - {{ object.body|title }}</li>
</ul>
<div class="col-10 mx-auto">
    <a type="button" title="Вернуться на главную" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:message_list' %}">Назад</a>
    <a type="button" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:message_update' object.pk %}">Редактировать</a>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
</div>
{% endblock %}

mailings/templates/mailings/mailingmessage_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">

        <form method="post" enctype="multipart/form-data">
            <div class="text-center">
                <p class="mt-4">Изменить Сообщение:</p>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a type="button" title="Вернуться на страницу сообщений" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'mailings:message_list' %}">Назад</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/mailingmessage_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h1 class="display-4 fw-normal">{{ title_name|title }} Hello</h1>
    <p class="fs-5 text-muted">Список сообщений</p>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:create_message' %}">Добавить сообщение</a>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3  col-10 mx-auto">
    {% for message in messages %}
    {% if user == message.owner %}
    <div class="col">
        <div class="card shadow-sm" style="min-width: 304px;">
            <div class="card-body">
                <p class="card-text">Тема - {{ message.theme|title }}</p>
                <p class="card-text">Содержание - {{ message.body|title }}</p>
                <div class="">
                    <div class="">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:message_detail' message.pk %}">Подробнее</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:message_update' message.pk %}">Редактировать</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:message_delete' message.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

mailings/templates/mailings/recipientclient_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h3>Хотите удалить клиента? {{ object.name }}</h3>
                    <button type="submit" class="btn btn-secondary">
                        Подтвердить
                    </button>
                    <a class="btn btn-success" href="{% url 'mailings:clients_list' %}">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/recipientclient_detail.html
{% extends 'mailings/base.html' %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h2 class="display-4 fw-normal">{{ object.email|title }}</h2>
</div>
<ul class="col-10 mx-auto">
    <li><b>Полное имя</b> - {{ object.full_name|title }}</li>
    <li><b>Комментарий</b> - {{ object.comment|title }}</li>
</ul>
<div class="col-10 mx-auto">
    <a type="button" title="Вернуться на главную" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:clients_list' %}">Назад</a>
    <a type="button" class="btn btn-sm btn-outline-secondary"
       href="{% url 'mailings:clients_update' object.pk %}">Редактировать</a>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:clients_delete' object.pk %}">Удалить</a>
</div>
{% endblock %}

mailings/templates/mailings/recipientclient_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">

        <form method="post" enctype="multipart/form-data">
            <div class="text-center">
                <p class="mt-4">Изменить данные клиента:</p>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a type="button" title="Вернуться к списку клиентов" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'mailings:clients_list' %}">Назад</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mailings/templates/mailings/recipientclient_list.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h1 class="display-4 fw-normal">{{ title_name|title }} Hello</h1>
    <p class="fs-5 text-muted">Список клиентов</p>
    <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:create_client' %}">Добавить клиента</a>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3  col-10 mx-auto">
    {% for client in clients %}
    {% if user == client.owner %}
    <div class="col">
        <div class="card shadow-sm" style="min-width: 304px;">
            <div class="card-body">
                <p class="card-text">Мэйл - {{ client.email|title }}</p>
                <p class="card-text">Имя - {{ client.full_name|title }}</p>
                <div class="">
                    <div class="">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:clients_detail' client.pk %}">Подробнее</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:clients_update' client.pk %}">Редактировать</a>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'mailings:clients_delete' client.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}