blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PublicationCreateView, PublicationListView, PublicationDetailView, PublicationUpdateView, \
    PublicationDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PublicationCreateView.as_view(), name='create'),
    path('', PublicationListView.as_view(), name='list'),
    path('view/<int:pk>', PublicationDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PublicationUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PublicationDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class Publication(models.Model):
    name = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug')
    description = models.CharField(max_length=150, verbose_name='содержимое', **NULLABLE)
    image = models.ImageField(upload_to='img_publication', verbose_name='превью', **NULLABLE)
    created_at = models.DateField(verbose_name='дата создания', auto_now_add=True)
    publication_activ = models.BooleanField(verbose_name='признак публикации', default=True)
    counter = models.IntegerField(verbose_name='количество просмотров', default=0)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

blog/forms.py
from django import forms
from blog.models import Publication
from mailings.forms import StyleFormMixin


class PublicationForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Publication
        fields = ('name', 'description', 'image', 'publication_activ', 'counter')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.forms import PublicationForm
from blog.models import Publication
from config.settings import EMAIL_HOST_USER

# Create your views here.
class PublicationCreateView(CreateView):
    model = Publication
    form_class = PublicationForm
    # fields = ('name', 'description', 'image', 'publication_activ', 'counter')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)

class PublicationListView(LoginRequiredMixin, ListView):
    model = Publication

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_activ=True)
        return queryset

class PublicationDetailView(DetailView):
    model = Publication

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.counter += 1
        self.object.save()
        if self.object.counter >= 100:
            send_mail(
                'Просмотры Блога',
                f'Ура! - публикация <{self.object}> набрала 100 просмотров...',
                EMAIL_HOST_USER,
                ['Sergo77644@yandex.ru',],
            )
        return self.object

class PublicationUpdateView(PermissionRequiredMixin, UpdateView):
    model = Publication
    form_class = PublicationForm
    permission_required = 'blog.change_publication'
    # fields = ('name', 'description', 'image', 'publication_activ', 'counter')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

class PublicationDeleteView(PermissionRequiredMixin, DeleteView):
    model = Publication
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_publication'

blog/templates/blog/publication_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <h3>Хотите удалить запись?{{ object.name }}</h3>
                    <button type="submit" class="btn btn-secondary">
                        Подтвердить
                    </button>
                    <a class="btn btn-success" href="{% url 'blog:list' %}">
                        Отмена
                    </a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/publication_detail.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <h2 class="display-4 fw-normal">{{ object.name }} / {{ object.slug }}</h2>
    <img src="{{ object.image | media_filter }}" class="col-2" style="height: 300px; width: max-content">
</div>
<ul class="col-10 mx-auto">
    <li>Содержание: {{ object.description | description_filter }}</li>
    <li>Просмотры: {{ object.counter }}</li>
</ul>
<div class="col-10 mx-auto">
    <a type="button" class="btn btn-sm btn-outline-secondary"
       href="{% url 'blog:list' %}">Назад</a>
</div>
{% endblock %}

blog/templates/blog/publication_form.html
{% extends 'mailings/base.html' %}

{% block content %}
    <div class="col-10 mx-auto">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">
              {% if object %}
              Сохранить
              {% else %}
              Создать
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
{% endblock %}

blog/templates/blog/publication_list.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">+</a>
</div>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 col-10 mx-auto">
    {% for object in object_list %}
    <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <p class="card-text">{{ object.name | title }}</p>
                <ul class="">
                    <li>Просмотры: {{ object.counter }}</li>
                </ul>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'blog:view' object.pk %}">View</a>
                        {% if user.is_authenticated %}
                        {% if perms.blog.change_publication %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'blog:edit' object.pk %}">Edit</a>
                        {% endif %}
                        {% if perms.blog.delete_publication %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'blog:delete' object.pk %}">Delete</a>
                        {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}