blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import PublicationCreateView, PublicationListView, PublicationDetailView, PublicationUpdateView, \
    PublicationDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', PublicationCreateView.as_view(), name='create'),
    path('', PublicationListView.as_view(), name='list'),
    path('view/<int:pk>', PublicationDetailView.as_view(), name='view'),
    path('edit/<int:pk>', PublicationUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', PublicationDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, email_verification, ProfileView, recovery_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("recovery_password/", recovery_password, name="recovery"),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}

# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    token = models.CharField(max_length=150, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.email}'

    class Meta:
        verbose_name = 'Пользователь'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Пользователи'  # Настройка для наименования набора объектов

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms
from mailings.forms import StyleFormMixin

class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

class RecoverPasswordForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

users/views.py
import secrets
from random import randint
import random
from django.contrib.auth.mixins import LoginRequiredMixin

from config.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse

from users.forms import UserRegisterForm
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView, TemplateView
from users.models import User
from mailings.models import Mailing, RecipientClient
from blog.models import Publication
from users.forms import UserProfileForm, RecoverPasswordForm

# Create your views here.

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        print('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ')
        user = form.save()
        user.is_active = False
        print(user)
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}/'
        send_mail(
            'Подтверждение почты',
            f'Перейдите по ссылке для подтверждения почты {url}',
            EMAIL_HOST_USER,
            [user.email],
        )
        return super().form_valid(form)

def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))

class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        mailings_all = Mailing.objects.filter(owner=user)
        mailings_active = Mailing.objects.filter(owner=user).filter(status='запущена')
        clients = RecipientClient.objects.filter(owner=user)
        clients_email = [client.email for client in clients]
        uni_clients_email = set(clients_email)
        list_blog = list(Publication.objects.all())
        random.shuffle(list_blog)
        context['mailings_all'] = len(mailings_all)
        context['mailings_active'] = len(mailings_active)
        context['uni_clients_email'] = len(uni_clients_email)
        context['list_blog'] = list_blog[:3]
        return context

def recovery_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        user = User.objects.get(email=email)
        new_password = "".join([str(randint(0, 9)) for i_ in range(8)])
        send_mail(
            "Восстановление доступа",
            f"Ваш новый пароль : {new_password}",
            EMAIL_HOST_USER,
            [user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse("users:login"))
    else:
        form = RecoverPasswordForm
        context = {"form": form}
        return render(request, "users/recovery_password_form.html", context)

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h2 class="mb-3">Вход</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Вход
                    </button>
                </form>
                <a class="btn btn-light mt-3 me-3 py-2 text-dark text-decoration-none" href="{% url 'users:recovery' %}">Восстановить пароль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/recovery_password_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h2 class="mb-3">Изменение пароля</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сменить
                    </button>
                </form>
                <p class="mt-3">На вашу почту будет отправлено письмо с новым паролем...</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <h2 class="mb-3">Регистрация</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Зарегистрироваться
                    </button>
                    <p class="mt-3">После регистрации на вашу почту будет отправлено сообщение со ссылкой - перейдите по ней что бы
                        подтвердить подлинность почты...</p>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <div class="pricing-header p-3 pb-md-4 mx-auto text-center col-10">
                    <h2 class="display-4 fw-normal">{{ user.email|title }}</h2>
                    <img src="{{ user.avatar | media_filter }}" class="col-2"
                         style="height: 300px; width: max-content">
                </div>
                <h2 class="mb-3">Профиль</h2>
                <ul class="col-10 mx-auto">
                    <li><b>Количество рассылок всего</b> - {{ mailings_all }}</li>
                    <li><b>Количество активных рассылок</b> - {{ mailings_active }}</li>
                    <li><b>Количество уникальных клиентов для рассылок</b> - {{ uni_clients_email }}</li>
                    <li>
                        <p class="mb-1"><b>Три случайные статьи из блога:</b></p>
                        {% for item in list_blog %}
                        <p class="mt-1 mb-0">- {{ item }}</p>
                        {% endfor %}
                    </li>
                </ul>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}